### ISSUE TITLE
Highlight First Letter of Each Word

### ISSUE THREAD

**Issue by CheesePizza100** [C485/CocoJumper#39]
The original EasyMotion plugin provides many ways for searching/navigating a document. There is a port for Visual Studio but it only allows for one character search (which Cocojumper already covers).

One of the many nice features it has is that you can give it a simple command and it will highlight the first letter of each word with a letter and you just press the letter that represents the word you want to jump to. It's not so much of a search as it is more of a....I want to jump to location X right now.

You can see examples on their github site. This is more of a feature request but you may feel that it does not fit with the purpose of Cocojumper.

[https://github.com/easymotion/vim-easymotion](url)

**Comment by C485** [comment]
Gonna look into this after #32  #24

**Comment by Kraviecc** [comment]
Working on it.

**Comment by Kraviecc** [comment]
The new feature is available on the marketplace.
